def split_str(text: str):
    return text.strip().split()


PORTRAITS = {
    'MAM': split_str("mam5 mam13 mam10 mam14 mam4 mam9 mam11 mam6 mam3 mam12 mam7 mam15 mam2 mam8 mam1 mam16"),
    'HUM': split_str(
        "human humanoid_02 humanoid_03 humanoid_04 humanoid_05 humanoid_hp_01 humanoid_hp_02 humanoid_hp_06 humanoid_hp_07 humanoid_hp_08 "
        "humanoid_hp_09 humanoid_hp_10 humanoid_hp_11 humanoid_hp_12 humanoid_hp_13"),
    'REP': split_str("rep2 "
                     "rep10 "
                     "rep14 "
                     "rep3 "
                     "rep7 "
                     "rep12 "
                     "rep9 "
                     "rep11 "
                     "rep6 "
                     "rep13 "
                     "rep1 "
                     "rep8 "
                     "rep4 "
                     "rep15 "
                     "rep5"),
    'AVI': split_str("avi1 "
                     "avi8 "
                     "avi13 "
                     "avi10 "
                     "avi15 "
                     "avi4 "
                     "avi7 "
                     "avi5 "
                     "avi9 "
                     "avi6 "
                     "avi11 "
                     "avi3 "
                     "avi14 "
                     "avi2 "
                     "avi12"),
    'ART': split_str("art14 "
                     "art7 "
                     "art12 "
                     "art6 "
                     "art1 "
                     "art13 "
                     "art8 "
                     "art3 "
                     "art5 "
                     "art9 "
                     "art10 "
                     "art11 " 
                     "art15 "
                     "art19"),
    'MOL': split_str("mol3 "
                     "mol7 "
                     "mol13 "
                     "mol2 "
                     "mol14 "
                     "mol4 "
                     "mol8 "
                     "mol1 "
                     "mol11 "
                     "mol12 " 
                     "mol5 "
                     "mol6 "
                     "mol15"),
    'FUN': split_str("fun2 "
                     "fun4 "
                     "fun3 "
                     "fun13 "
                     "fun12 "
                     "fun6 "
                     "fun15 "
                     "fun7 "
                     "fun1 "
                     "fun9 "
                     "fun11 "
                     "fun8 "
                     "fun14 "
                     "fun10"),
    'PLANT': split_str("pla2 "
                       "pla6 "
                       "pla1 "
                       "pla11 "
                       "pla3 "
                       "pla13 "
                       "pla7 "
                       "pla15 "
                       "pla10 "
                       "pla5 "
                       "pla9 "
                       "pla14 "
                       "pla4 "
                       "pla8 "
                       "pla12"),
    'LITHOID': split_str("lith1 "
                         "lith2 "
                         "lith3 "
                         "lith4 "
                         "lith5 "
                         "lith6 "
                         "lith7 "
                         "lith8 "
                         "lith9 "
                         "lith10 "
                         "lith11 "
                         "lith12 "
                         "lith13 "
                         "lith14 "
                         "lith15"),
    'ROBOT': split_str("sd_hum_robot "
                       "sd_mam_robot "
                       "sd_rep_robot "
                       "sd_avi_robot "
                       "sd_art_robot "
                       "sd_mol_robot "
                       "sd_fun_robot "
                       "sd_pla_robot")
}